# Generated by Django 4.1 on 2023-06-28 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('cretate_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cretate_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('name', models.CharField(max_length=20, verbose_name='カテゴリー')),
                ('url', models.URLField(verbose_name='URL')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cretate_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('name', models.CharField(max_length=100, verbose_name='商品名')),
                ('url', models.URLField(verbose_name='商品URL')),
                ('store', models.CharField(max_length=100, verbose_name='店舗名')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('price_fluctuation', models.IntegerField(blank=True, verbose_name='変動価格')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rakuten.categories')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
